version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            #pip install -r requirements.txt
                #- apt-get install build-essential libncursesw5-dev libgdbm-dev libc6-dev zlib1g-dev libsqlite3-dev tk-dev libssl-dev openssl libbz2-dev libreadline-dev
     
            sudo sh sh/install-cuda-10-0.sh 
          # setup python testing environments
            
        
        
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator
